name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Type-check library
        run: npm run typecheck

      # - name: Lint (Biome)
      #   run: npm run check

      - name: Build Next.js app
        run: npm -w apps/zoutex-playground run build

      - name: Run unit tests
        run: npm test -- --reporter=verbose --reporter=junit --outputFile=test-results.xml

      - name: Run integration tests
        run: npm -w apps/zoutex-playground run test -- --reporter=verbose --reporter=junit --outputFile=test-results.xml

      - name: Publish unit test results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: Unit Test Report
          report_paths: test-results.xml

      - name: Publish integration test results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: Integration Test Report
          report_paths: apps/zoutex-playground/test-results.xml
